version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload